export const CAR_LIST_REQUEST = "CAR_LIST_REQUEST";
export const CAR_LIST_SUCCESS = "CAR_LIST_SUCCESS";
export const CAR_LIST_FAIL = "CAR_LIST_FAIL";

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST";
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS";
export const CAR_DETAILS_FAIL = "CAR_DETAILS_FAIL";
export const CAR_DETAILS_RESET = "CAR_DETAILS_RESET";

export const CAR_DELETE_REQUEST = "CAR_DELETE_REQUEST";
export const CAR_DELETE_SUCCESS = "CAR_DELETE_SUCCESS";
export const CAR_DELETE_FAIL = "CAR_DELETE_FAIL";

export const CAR_CREATE_REQUEST = "CAR_CREATE_REQUEST";
export const CAR_CREATE_SUCCESS = "CAR_CREATE_SUCCESS";
export const CAR_CREATE_FAIL = "CAR_CREATE_FAIL";
export const CAR_CREATE_RESET = "CAR_CREATE_RESET";

export const CAR_UPDATE_REQUEST = "CAR_UPDATE_REQUEST";
export const CAR_UPDATE_SUCCESS = "CAR_UPDATE_SUCCESS";
export const CAR_UPDATE_FAIL = "CAR_UPDATE_FAIL";
export const CAR_UPDATE_RESET = "CAR_UPDATE_RESET";

export const CAR_RESERVATION_REQUEST = "CAR_RESERVATION_REQUEST";
export const CAR_RESERVATION_SUCCESS = "CAR_RESERVATION_SUCCESS";
export const CAR_RESERVATION_FAIL = "CAR_RESERVATION_FAIL";
export const CAR_RESERVATION_RESET = "CAR_RESERVATION_RESET";
